version: 2 
jobs:
  build:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mysql:8.0.4
        environment: 
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout    
      - run: 
           name: Install MySQL CLI; Import dummy data; run an example query
           command: | 
             sudo apt-get install default-mysql-client
             mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
             mysql -h 127.0.0.1 -u user -ppassw0rd --execute="Select * from test_db.Persons"
workflows:
  version: 2
  build-deploy
    jobs:
      - build
